# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVM 예제' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'
  # Pods for MVVM 예제

  target 'MVVM 예제Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVM 예제UITests' do
    # Pods for testing
  end

end
